version: "3.8"
services:
  app:
    environment:
      - CONFIG_FILE_NAME=config.compose
    container_name: skel_ws
    build: .
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - fullstack

  mysql:
    image: mysql:latest
    container_name: skel_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=skel
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - fullstack
    healthcheck:
      test: "exit 0"

  redis:
    image: redis:latest
    container_name: skel_redis
    ports:
      - "6379:6379"
    networks:
      - fullstack
    healthcheck:
      test: "exit 0"

volumes:
  api:
  database_mysql:

networks:
  fullstack:
    driver: bridge
