app:
  name: "skel"
  ver: "0.0"
  port: "8000"
  env: "dev"
db:
  mysql:
    username: ""
    password: ""
    host: ""
    port: ""
    name: ""
    connection:
      maxIdle: 10
      maxOpen: 100
      maxLifetime: "1h"
  redis:
    host: ""
    port: ""
    password: ""
    dbNum: 10
log:
  severityLevel: 7
constants:
  accessTokenName: "access_token:"
  accessTokenTTL: "15m"
  accessTokenSecret: ""
  refreshTokenName: "refresh_token:"
  refreshTokenTTL: "72h"
  refreshTokenSecret: ""
